config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    resources :customers, only: [:show, :index, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'customers/mypage' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get  'customers/unsubscribe' => 'customers#unsubscribe', as:'unsubscribe' #確認画面へのパス
    patch 'customers/withdraw' => 'customers#withdraw', as:'withdraw' #退会処理用のアクションパス
    get 'orders/done'
    post 'orders/confirm'
    resources :genres, only: [:show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
  end

  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 検索機能のルーティング
  get 'search', to: 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_detail, dependent: :destroy
  
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の数字のみで入力してください（ハイフンなし）" }
  validates :address, :name, presence: true

  enum status: {
    waiting_for_payment: 0,  # 入金待ち
    payment_confirmed: 1,    # 入金確認
    in_production: 2,        # 製作中
    preparing_for_shipment: 3, # 発送準備中
    shipped: 4               # 発送済み
  }

  enum payment_method: { credit_card: 0, transfer: 1 }

  # ステータスの日本語化
  def self.statuses_i18n
    statuses.keys.map { |key| [I18n.t("enums.order.status.#{key}"), key] }
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_detail
    @customer_name = @order.customer.family_name + @order.customer.first_name
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_detail
        if  @order.update(order_params)
      @order_details.update_all(making_status: "wait") if @order.status == "payment_confirmed"
    end
      redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div>
  <%= flash[:notice] %>
</div>



<div class="container">
  <div class="row my-3">
    <h3 class="d-inline-block p-2 m-4", style="background-color: #e0e0e0; color: #333;">注文履歴詳細</h3>
  </div>
  <div class="row">
    <div class="col-3">
      <strong>購入者</strong>
    </div>
    <div class="col-4">
      <%= link_to @customer_name, admin_customer_path, class:"text-dark" %>
    </div>
  </div>
  <div class="row">
    <div class="col-3">
      <strong>注文日</strong>
    </div>
    <div class="col-4" >
      <%= @order.created_at.strftime("%Y/%m/%d") %>
    </div>
  </div>
  <div class="row">
    <div class="col-3">
      <strong>配送先</strong>
    </div>
    <div class="col-4" >
      <div class = "row">
        〒<%= @order.postal_code %>  <%= @order.address %>
      </div>
      <div class = "row">
        <%= @order.name %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-3">
      <strong>支払方法</strong>
    </div>
    <div class="col-4" >
      <%= I18n.t("enums.order.payment_method.#{@order.payment_method}") %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-3">
      <strong>注文ステータス</strong>
    </div>
    <%= form_with model: @order,url: admin_order_path(@order), method: :patch, local: true do |f| %>
    <div class="col-4 d-flex">
      <div>
        <%= f.select :status, options_for_select(Order.statuses_i18n, @order.status), class: "form-select w-auto" %>
      </div>
      <div class="ml-5">
        <%= f.submit "更新", class: "btn btn-success" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <table class="table col-lg-8">
      <thead style="background-color: #f1f1f1; color: #333;">
        <tr>
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= (order_detail.item.price * 1.1).to_i.to_s(:delimited) %></td>
            <td><%= order_detail.amount_ordered %></td>
            <td><%= (order_detail.item.price * 1.1 * order_detail.amount_ordered).to_i.to_s(:delimited) %></td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true do |f| %>
            <td>
              <div class="d-flex">
                <%= f.select :making_status, 
                  options_for_select(OrderDetail.making_statuses.keys.map { |key| [OrderDetail.making_statuses_i18n[key], key] }, order_detail.making_status), 
                  class: "form-select w-auto" %>
              </div>
            </td>
            <td>
              <%= f.submit "更新", class: "btn btn-success ms-2" %>
            </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="col-lg-4 justify-content-center mt-auto mb-3">
      <div class="row">
        <div class="col-6">
          <strong>商品合計</strong>
        </div>
        <div class="col-6">
          <%= @order.total_payment.to_s(:delimited) %>円
        </div>
      </div>
      <div class="row">
        <div class="col-6">
          <strong>送料</strong>
        </div>
        <div class="col-6">
          <%= @order.shipping_cost %>円
        </div>
      </div>
      <div class="row">
        <div class="col-6">
          <strong>請求金額合計</strong>
        </div>
        <div class="col-6">
          <strong><%= (@order.total_payment + @order.shipping_cost).to_s(:delimited) %>円</strong>
        </div>
      </div>
    </div>
  </div>
</div>