config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    resources :customers, only: [:show, :index, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'customers/mypage' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get  'customers/unsubscribe' => 'customers#unsubscribe', as:'unsubscribe' #確認画面へのパス
    patch 'customers/withdraw' => 'customers#withdraw', as:'withdraw' #退会処理用のアクションパス
    get 'orders/done'
    post 'orders/confirm'
    resources :genres, only: [:show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
  end

  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 検索機能のルーティング
  get 'search', to: 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の数字のみで入力してください（ハイフンなし）" }
  validates :address, presence: true
  validates :name, presence: true

  # view/pubric/orders/new.html.erbで使うメソッド
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders
  has_many :addresses,  dependent: :destroy
  
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の数字のみで入力してください（ハイフンなし）" }
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/, message: "は10桁もしくは11桁の数字のみで入力してください（ハイフンなし）"}
  validates :email, uniqueness: true

  def active_for_authentication?
    super && (is_active == true)
  end

  # 検索機能のためのメソッド
  scope :search_by_fullname, ->(query, match_type) {
    case match_type
    when 'partial' then where("CONCAT(family_name, first_name) LIKE ?", "%#{query}%")
    else all
    end
  }

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre
  has_one_attached :item_image

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :item_image, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

  # 検索機能のためのメソッド
  scope :search_by_name, ->(query, match_type) {
    case match_type
    when 'partial' then where('name LIKE ?', "%#{query}%")
    else all
    end
  }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_detail, dependent: :destroy
  
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の数字のみで入力してください（ハイフンなし）" }
  validates :address, :name, presence: true

  enum status: {
    waiting_for_payment: 0,  # 入金待ち
    payment_confirmed: 1,    # 入金確認
    in_production: 2,        # 製作中
    preparing_for_shipment: 3, # 発送準備中
    shipped: 4               # 発送済み
  }

  enum payment_method: { credit_card: 0, transfer: 1 }

  # ステータスの日本語化
  def self.statuses_i18n
    statuses.keys.map { |key| [I18n.t("enums.order.status.#{key}"), key] }
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { not_available: 0, wait: 1, making: 2, complete:3 }

  # view/pub/orders/show で使用
  def subtotal
    (price_including_tax * amount_ordered).to_i
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
    @btn_text = "新規登録"
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルを追加しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
    @btn_text = "変更を保存"
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルを変更しました"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
    @btn_text = '新規登録'
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の新規登録が完了しました"
      redirect_to admin_item_path(@item)
    else
      flash.now[:notice] = "予期せぬエラーが発生しました"
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @btn_text = '変更を保存'
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "変更が完了しました"
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :name, :description, :price, :is_active, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @query = params[:query]
    @search_type = params[:search_type]  # 会員検索 or 商品検索
    @match_type = params[:match_type]    # 部分一致

    if @search_type == 'Customer'
      @results = Customer.search_by_fullname(@query, @match_type)
    elsif @search_type == 'Item'
      @results = Item.search_by_name(@query, @match_type)
      @pub_results = Item.where(is_active: true).search_by_name(@query, @match_type)
    else
      @results = []  # どちらにも該当しない場合、@results は空の配列 [] になる
    end

    render 'searches/search_results'
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/homes/top.html.erb
<div class="container-fluid position-relative">
  <div class="row align-items-center justify-content-center">
    <div class="col-lg-10 col-md-8">
      <h5 class="d-inline-block p-2 m-4" style="background-color: #E0E0E0; color: #333;">注文履歴一覧</h5>
      <table class="table">
        <thead style="background-color: #E0E0E0; color: #333;">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M"), admin_order_path(order) %></td>
              <td><%= order.customer.family_name %><%= order.customer.first_name %></td>
              <td><%= order.order_detail.sum(:amount_ordered) %></td>
              <td><%= I18n.t("enums.order.status.#{order.status}") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="col-12 d-flex justify-content-center">
        <%= paginate @orders %>
      </div>
    </div>
  </div>
</div>

app/views/searches/search_results.html.erb
<div class='container'>
  <div class="row">
    <% if @search_type == 'Customer' %>
      <h4 class="d-inline-block p-2 m-4", style="background-color: #e0e0e0; color: #333;">
        "<%= @query %>" で 会員を検索
      </h4>
    <% else @search_type == 'Item' %>
      <h4 class="d-inline-block p-2 m-4", style="background-color: #e0e0e0; color: #333;">
        "<%= @query %>" で 商品を検索
      </h4>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% if @results.any? %>
        <table class ="table">
          <!-- 会員についての検索結果 -->
          <% if @search_type == 'Customer' %>
            <thead style="background-color: #f1f1f1; color: #333;">
              <tr>
                <th>会員ID</th>
                <th>氏名</th>
                <th>メールアドレス</th>
                <th>ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @results.each do |result| %>
                <tr>
                  <td>
                    <%= result.id %>
                  </td>
                  <td>
                    <%= link_to "#{result.family_name}#{result.first_name}", admin_customer_path(result), class: 'text-dark' %>
                  </td>
                  <td>
                    <%= result.email %>
                  </td>
                  <td class="<%= result.is_active ? 'text-success font-weight-bold' : 'text-muted font-weight-bold' %>">
                    <%= result.is_active ? '有効' : '退会' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          <!-- 商品についての検索結果 -->
          <% elsif @search_type == 'Item' %>
            <!-- 管理者ログイン時 -->
            <% if admin_signed_in? %>
              <thead style="background-color: #f1f1f1; color: #333;">
                <tr>
                  <th>商品ID</th>
                  <th>商品名</th>
                  <th>税抜価格</th>
                  <th>ジャンル</th>
                  <th>ステータス</th>
                </tr>
              </thead>
              <tbody>
                <% @results.each do |result| %>
                  <tr>
                    <td class="align-middle">
                      <%= result.id %>
                    </td>
                    <td class="align-middle">
                      <%= link_to admin_item_path(result.id), class: 'text-dark' do %>
                        <%= result.name %>
                      <% end %>
                    </td>
                    <td class="align-middle">
                      <%= result.price.to_s(:delimited) %>
                    </td>
                    <td class="align-middle">
                      <%= result.genre.name %>
                    </td>
                    <td class="align-middle">
                      <% if result.is_active %>
                        <p class="text-success font-weight-bold">販売中</p>
                      <% else %>
                        <p class="text-muted font-weight-bold">販売停止中</p>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            <!-- 会員ログインまたは未ログイン時 -->
            <% else %>
              <thead style="background-color: #f1f1f1; color: #333;">
                <tr>
                  <th>商品名</th>
                  <th>商品説明</th>
                  <th style="white-space: nowrap;">税込価格</th>
                </tr>
              </thead>
              <tbody>
                <% @pub_results.each do |result| %>
                  <tr>
                    <td style="white-space: nowrap;">
                      <%= image_tag result.item_image, size: "40x40" %>
                      <%= link_to result.name, item_path(result.id) %>
                    </td>
                    <td>
                      <%= result.description %>
                    </td>
                    <td>
                      <%= result.with_tax_price.to_s(:delimited) %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            <% end %>
          <% end %>
        </table>
      <% else %>
        <p>該当する結果は見つかりませんでした。</p>
      <% end %>
    </div>
  </div>
</div>