config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    resources :customers, only: [:show, :index, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'customers/mypage' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get  'customers/unsubscribe' => 'customers#unsubscribe', as:'unsubscribe' #確認画面へのパス
    patch 'customers/withdraw' => 'customers#withdraw', as:'withdraw' #退会処理用のアクションパス
    get 'orders/done'
    post 'orders/confirm'
    resources :genres, only: [:show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
  end

  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 検索機能のルーティング
  get 'search', to: 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の数字のみで入力してください（ハイフンなし）" }
  validates :address, presence: true
  validates :name, presence: true

  # view/pubric/orders/new.html.erbで使うメソッド
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders
  has_many :addresses,  dependent: :destroy
  
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の数字のみで入力してください（ハイフンなし）" }
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/, message: "は10桁もしくは11桁の数字のみで入力してください（ハイフンなし）"}
  validates :email, uniqueness: true

  def active_for_authentication?
    super && (is_active == true)
  end

  # 検索機能のためのメソッド
  scope :search_by_fullname, ->(query, match_type) {
    case match_type
    when 'partial' then where("CONCAT(family_name, first_name) LIKE ?", "%#{query}%")
    else all
    end
  }

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre
  has_one_attached :item_image

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :item_image, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

  # 検索機能のためのメソッド
  scope :search_by_name, ->(query, match_type) {
    case match_type
    when 'partial' then where('name LIKE ?', "%#{query}%")
    else all
    end
  }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_detail, dependent: :destroy
  
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の数字のみで入力してください（ハイフンなし）" }
  validates :address, :name, presence: true

  enum status: {
    waiting_for_payment: 0,  # 入金待ち
    payment_confirmed: 1,    # 入金確認
    in_production: 2,        # 製作中
    preparing_for_shipment: 3, # 発送準備中
    shipped: 4               # 発送済み
  }

  enum payment_method: { credit_card: 0, transfer: 1 }

  # ステータスの日本語化
  def self.statuses_i18n
    statuses.keys.map { |key| [I18n.t("enums.order.status.#{key}"), key] }
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { not_available: 0, wait: 1, making: 2, complete:3 }

  # view/pub/orders/show で使用
  def subtotal
    (price_including_tax * amount_ordered).to_i
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
    @btn_text = '新規登録'
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の新規登録が完了しました"
      redirect_to admin_item_path(@item)
    else
      flash.now[:notice] = "予期せぬエラーが発生しました"
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @btn_text = '変更を保存'
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "変更が完了しました"
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :name, :description, :price, :is_active, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @query = params[:query]
    @search_type = params[:search_type]  # 会員検索 or 商品検索
    @match_type = params[:match_type]    # 部分一致

    if @search_type == 'Customer'
      @results = Customer.search_by_fullname(@query, @match_type)
    elsif @search_type == 'Item'
      @results = Item.search_by_name(@query, @match_type)
      @pub_results = Item.where(is_active: true).search_by_name(@query, @match_type)
    else
      @results = []  # どちらにも該当しない場合、@results は空の配列 [] になる
    end

    render 'searches/search_results'
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_message.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger">
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="container-fluid pt-5 bg-dark min-vh-10">
      <div class="row">

      </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">

      <div class="row justify-content-start">
        <a class="navbar-brand" href="/">
          <%= link_to '/' do %>
            <%= image_tag 'nagano_cake_ロゴ_黒-removebg-preview.png', width: 250, height: 75, class: "img-resize rounded " %>
          <% end %>
        </a>
      </div>

      <div class = "row">
        <div class="col-lg-12">
          <div class="row justify-content-end mr-2">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
          <div class="row  justify-content-end mr-2 collapse navbar-collapse justify-content-lg-end" id="navbarNavDropdown">
            <ul class="navbar-nav d-flex flex-lg-row flex-wrap">
              <% if admin_signed_in? %>
                <li>
                  <%= link_to admin_items_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-cake-candles"></i> 商品一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_customers_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-users"></i> 会員一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_root_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-barcode"></i> 注文履歴一覧
                  <% end %>
                  </li>
                <li>
                  <%= link_to admin_genres_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-shapes"></i> ジャンル一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_admin_session_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-right-from-bracket"></i> ログアウト
                  <% end %>
                </li>
              <% elsif customer_signed_in? %>
                <li>
                  <%= link_to customers_mypage_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-user"></i> マイページ
                  <% end %>
                </li>
                <li>
                  <%= link_to items_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-cake-candles"></i> 商品一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to cart_items_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-cart-shopping"></i> カート
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_customer_session_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-right-from-bracket"></i> ログアウト
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to about_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-house">About</i>
                  <% end %>
                <li>
                  <%= link_to items_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-cake-candles"></i> 商品一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to new_customer_registration_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-user-plus"></i> 新規登録
                  <% end %>
                </li>
                <li>
                  <%= link_to new_customer_session_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-right-to-bracket"></i> ログイン
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
          <div class= "row justify-content-end mt-1 mr-1">
            <div class="col-12  d-flex justify-content-end">
              <%= form_with url: search_path, method: :get, local: true do |f| %>
                <%= f.text_field :query, required: true %>
          
                <% if admin_signed_in? %>
                  <%= f.select :search_type, [['会員', 'Customer'], ['商品', 'Item']] %>
                <% else %>
                  <%= f.hidden_field :search_type, value: 'Item' %>
                <% end %>
          
                <%= f.hidden_field :match_type, value: 'partial' %>
                <%= f.submit "検索" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/cad58204f4.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %> 
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>